
#include "VectorEngineSite.buildv1.1.15/windows_release_mx/include/VectorEngineSite_std_collections_2container.h"

t_std_collections_IContainer_1Tt_VectorSite_VectorUIForm_2::~t_std_collections_IContainer_1Tt_VectorSite_VectorUIForm_2(){
}

t_std_collections_IIterator_1Tt_VectorSite_VectorUIForm_2::~t_std_collections_IIterator_1Tt_VectorSite_VectorUIForm_2(){
}

void mx2_VectorEngineSite_std_collections_2container_init_f(){
}
